"use client";
import {useEffect,useState} from "react";import AppNav from"@/app/components/AppNav";
import Link from "next/link";import{LanguageSwitch,useLanguage}from"@/app/i18n";
import {createClient} from "@/lib/supabase/client";
export default function Analytics(){const{lang,t}=useLanguage();
 const[d,setD]=useState<any>(null);
 useEffect(()=>{void load()},[]);
 async function load(){const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){window.location.href="/login";return}const{data:c}=await s.from("companies").select("*").eq("owner_id",user.id).limit(1).single();if(!c)return;const[cv,ld,qt,tm]=await Promise.all([s.from("conversations").select("id,channel,ai_employee_id").eq("company_id",c.id),s.from("leads").select("stage,value,ai_employee_id").eq("company_id",c.id),s.from("quotations").select("amount,status").eq("company_id",c.id),s.from("ai_employees").select("id,name").eq("company_id",c.id)]);const conversations=cv.data||[],leads=ld.data||[],team=tm.data||[];const channels=["whatsapp","website","instagram","facebook"].map(name=>({name,count:conversations.filter((x:any)=>x.channel===name).length}));const employees=team.map((e:any)=>({name:e.name,conversations:conversations.filter((x:any)=>x.ai_employee_id===e.id).length,leads:leads.filter((x:any)=>x.ai_employee_id===e.id).length,wins:leads.filter((x:any)=>x.ai_employee_id===e.id&&x.stage==="won").length,revenue:leads.filter((x:any)=>x.ai_employee_id===e.id&&x.stage==="won").reduce((a:number,x:any)=>a+Number(x.value||0),0)}));setD({company:c,conversations:conversations.length,leads:leads.length,qualified:leads.filter((x:any)=>x.stage==="qualified").length,quotes:(qt.data||[]).length,wins:leads.filter((x:any)=>x.stage==="won").length,revenue:leads.filter((x:any)=>x.stage==="won").reduce((a:number,x:any)=>a+Number(x.value||0),0),channels,employees})}
 if(!d)return <main className="loading">{lang==="ar"?"جاري تحميل التحليلات…":"Loading analytics…"}</main>;
 const max=Math.max(1,...d.channels.map((x:any)=>x.count));
 return <main className="appshell"><AppNav/><div className="appbody"><main className="module"><header><Link href="/dashboard">← Dashboard</Link><div className="logo"><i>N</i><b>NAYROQ</b></div><span>{lang==="ar"?"التحليلات":"Analytics"}</span><LanguageSwitch/></header><section><div className="eyebrow">{lang==="ar"?"الأداء":"PERFORMANCE"}</div><h1>{lang==="ar"?"تحليلات فريق الذكاء الاصطناعي.":"AI workforce analytics."}</h1><p>{t("livePerformance")}</p><div className="managerstats">{[["Conversations",d.conversations],["Leads",d.leads],["Qualified",d.qualified],["Quotations",d.quotes],["Won",d.wins],["Revenue",d.revenue+" "+d.company.currency]].map((x:any)=><div className="stat" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div><div className="analyticsgrid"><div className="panel"><h3>{t("conversationChannel")}</h3>{d.channels.map((x:any)=><div className="channelbar" key={x.name}><span>{x.name}</span><div><i style={{width:(x.count/max*100)+"%"}}/></div><b>{x.count}</b></div>)}</div><div className="panel"><h3>{t("employeePerformance")}</h3>{d.employees.length?d.employees.map((x:any)=><div className="performer" key={x.name}><div><b>{x.name}</b><small>{x.conversations} conversations · {x.leads} leads · {x.wins} won</small></div><strong>{x.revenue} {d.company.currency}</strong></div>):<div className="placeholder">{lang==="ar"?"لا توجد بيانات أداء للموظفين بعد.":"No employee performance data yet."}</div>}</div></div></section></main></div></main>
}