"use client";import{useEffect,useState}from"react";import Link from"next/link";import{createClient}from"@/lib/supabase/client";import{LanguageSwitch,useLanguage}from"@/app/i18n";
export default function Admin(){const{lang}=useLanguage();const ar=lang==="ar";const[data,setData]=useState<any>(null);const[forbidden,setForbidden]=useState(false);const[view,setView]=useState("overview");const[busy,setBusy]=useState("");
async function api(method="GET",body?:any){const s=createClient();const{data:{session}}=await s.auth.getSession();if(!session){location.href="/login";return null}const r=await fetch("/api/admin",{method,headers:{"Content-Type":"application/json","Authorization":"Bearer "+session.access_token},body:body?JSON.stringify(body):undefined});if(r.status===403){setForbidden(true);return null}return r.json()}
async function load(){const x=await api();if(x)setData(x)}useEffect(()=>{load()},[]);
async function review(id:string,action:string){setBusy(id);await api("POST",{paymentId:id,action});await load();setBusy("")}
async function receipt(path:string){const s=createClient();const{data:{session}}=await s.auth.getSession();if(!session)return;const r=await fetch("/api/admin/receipt",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+session.access_token},body:JSON.stringify({path})});const x=await r.json();if(x.url)window.open(x.url,"_blank");else alert(x.error||(ar?"تعذر فتح الإيصال":"Could not open receipt"))}
if(forbidden)return <main className="errorpage"><h1>{ar?"غير مصرح لك بالدخول":"Access denied"}</h1></main>;if(!data)return <main className="loading">{ar?"جاري تحميل لوحة الإدارة…":"Loading admin dashboard…"}</main>;
const pending=data.payments.filter((p:any)=>p.status==="pending"),approved=data.payments.filter((p:any)=>p.status==="approved"),active=data.companies.filter((c:any)=>c.subscription_status==="active"),trials=data.companies.filter((c:any)=>c.subscription_status==="trialing"),revenue=approved.reduce((n:number,p:any)=>n+Number(p.amount||0),0);
const nav=[["overview","⌂",ar?"لوحة التحكم":"Dashboard"],["companies","▦",ar?"الشركات":"Companies"],["payments","▣",ar?"الدفعات":"Payments"],["employees","◆",ar?"موظفو AI":"AI Employees"]];
return <main className="sa-shell"><aside className="sa-sidebar"><div className="sa-logo"><div className="logo"><i>N</i><b>NAYROQ</b></div><span>Your AI Workforce</span></div><nav>{nav.map(n=><button key={n[0]} className={view===n[0]?"active":""} onClick={()=>setView(n[0])}><i>{n[1]}</i><b>{n[2]}</b>{n[0]==="payments"&&pending.length>0&&<em>{pending.length}</em>}</button>)}</nav><div className="sa-sidebottom"><Link href="/dashboard">↗ {ar?"لوحة المستخدم":"User Dashboard"}</Link><LanguageSwitch/></div></aside>
<div className="sa-work"><header className="sa-top"><div className="sa-search">{ar?"إدارة كاملة لجميع الشركات والاشتراكات في NAYROQ":"Complete control of companies and subscriptions in NAYROQ"}</div><div className="sa-profile"><div><b>Odai Shammas</b><span>Super Admin</span></div><i>O</i></div></header><div className="sa-content">
{view==="overview"&&<><div className="sa-welcome"><div><small>{ar?"لوحة التحكم":"CONTROL CENTER"}</small><h1>{ar?"مرحباً عدي 👋":"Welcome, Odai 👋"}</h1><p>{ar?"هنا يمكنك متابعة المنصة بالكامل من مكان واحد.":"Monitor and manage the entire platform from one place."}</p></div><button onClick={()=>setView("companies")}>+ {ar?"عرض الشركات":"View Companies"}</button></div>
<div className="sa-kpis"><K icon="▦" n={data.companies.length} t={ar?"الشركات":"Companies"} s={active.length+" "+(ar?"نشطة":"active")}/><K icon="◆" n={data.employees.length} t={ar?"موظفو AI":"AI Employees"} s={data.employees.filter((e:any)=>e.status==="active").length+" "+(ar?"نشط":"active")}/><K icon="▣" n={pending.length} t={ar?"دفعات بانتظار المراجعة":"Pending Payments"} s={ar?"تحتاج إجراء":"needs action"} warn/><K icon="◈" n={revenue+" OMR"} t={ar?"الإيرادات المعتمدة":"Approved Revenue"} s={approved.length+" "+(ar?"دفعة":"payments")}/></div>
<div className="sa-grid"><section className="sa-card wide"><Title t={ar?"الدفعات المعلقة":"Pending Payments"} n={pending.length}/><PaymentTable rows={pending.slice(0,4)} ar={ar} review={review} receipt={receipt} busy={busy}/>{pending.length>4&&<button className="sa-more" onClick={()=>setView("payments")}>{ar?"عرض الكل":"View all"} →</button>}</section><section className="sa-card"><Title t={ar?"حالة الاشتراكات":"Subscription Status"}/><div className="sa-status"><Stat n={active.length} t={ar?"نشطة":"Active"} c="green"/><Stat n={trials.length} t={ar?"تجربة":"Trial"} c="blue"/><Stat n={data.companies.length-active.length-trials.length} t={ar?"غير نشطة":"Inactive"} c="gray"/></div><div className="sa-revenue"><span>{ar?"إجمالي الدفعات المعتمدة":"Approved payments"}</span><strong>{revenue} OMR</strong></div></section></div>
<div className="sa-grid bottom"><section className="sa-card wide"><Title t={ar?"أحدث الشركات":"Recent Companies"} n={data.companies.length}/><CompanyTable rows={data.companies.slice(0,5)} ar={ar}/></section><section className="sa-card"><Title t={ar?"روابط سريعة":"Quick Actions"}/><div className="sa-actions"><button onClick={()=>setView("payments")}>▣<span>{ar?"مراجعة الدفعات":"Review Payments"}</span></button><button onClick={()=>setView("companies")}>▦<span>{ar?"إدارة الشركات":"Manage Companies"}</span></button><button onClick={()=>setView("employees")}>◆<span>{ar?"موظفو AI":"AI Employees"}</span></button><Link href="/billing">◈<span>{ar?"الفوترة":"Billing"}</span></Link></div></section></div></>}
{view==="companies"&&<section className="sa-card page"><Title t={ar?"جميع الشركات":"All Companies"} n={data.companies.length}/><CompanyTable rows={data.companies} ar={ar} full/></section>}
{view==="payments"&&<section className="sa-card page"><Title t={ar?"جميع الدفعات":"All Payments"} n={data.payments.length}/><PaymentTable rows={data.payments} ar={ar} review={review} receipt={receipt} busy={busy}/></section>}
{view==="employees"&&<section className="sa-card page"><Title t={ar?"موظفو الذكاء الاصطناعي":"AI Employees"} n={data.employees.length}/><div className="sa-table emp"><div className="sa-row head"><span>ID</span><span>{ar?"الشركة":"Company"}</span><span>{ar?"الحالة":"Status"}</span></div>{data.employees.map((e:any)=><div className="sa-row" key={e.id}><code>{e.id.slice(0,8)}…</code><b>{data.companies.find((c:any)=>c.id===e.company_id)?.name||"—"}</b><Badge v={e.status} ar={ar}/></div>)}</div></section>}
</div></div></main>}
function K({icon,n,t,s,warn}:any){return <article className={"sa-kpi "+(warn&&Number(n)>0?"warn":"")}><i>{icon}</i><div><strong>{n}</strong><b>{t}</b><span>{s}</span></div></article>}
function Title({t,n}:any){return <div className="sa-title"><h2>{t}</h2>{n!==undefined&&<em>{n}</em>}</div>}
function Stat({n,t,c}:any){return <div><i className={c}/><span>{t}</span><strong>{n}</strong></div>}
function Badge({v,ar}:any){const x:any={pending:ar?"بانتظار المراجعة":"Pending",approved:ar?"معتمدة":"Approved",rejected:ar?"مرفوضة":"Rejected",trialing:ar?"تجربة":"Trial",active:ar?"نشط":"Active"};return <em className={"sa-badge "+v}>{x[v]||v}</em>}
function PaymentTable({rows,ar,review,receipt,busy}:any){return <div className="sa-table pay"><div className="sa-row head"><span>{ar?"الشركة":"Company"}</span><span>{ar?"الخطة":"Plan"}</span><span>{ar?"المبلغ":"Amount"}</span><span>{ar?"الحالة":"Status"}</span><span>{ar?"التاريخ":"Date"}</span><span>{ar?"الإجراءات":"Actions"}</span></div>{rows.length?rows.map((p:any)=><div className="sa-row" key={p.id}><div className="sa-company"><i>{(p.companies?.name||"N")[0].toUpperCase()}</i><div><b>{p.companies?.name||"—"}</b><small>{p.reference}</small></div></div><b>{p.plan}</b><strong>{p.amount} {p.currency}</strong><Badge v={p.status} ar={ar}/><small>{new Date(p.submitted_at).toLocaleDateString(ar?"ar-OM":"en-GB")}</small><div className="sa-rowactions">{p.receipt_url&&<button onClick={()=>receipt(p.receipt_url)}>{ar?"الإيصال":"Receipt"}</button>}{p.status==="pending"&&<><button className="ok" disabled={busy===p.id} onClick={()=>review(p.id,"approve")}>{ar?"موافقة":"Approve"}</button><button className="no" disabled={busy===p.id} onClick={()=>review(p.id,"reject")}>{ar?"رفض":"Reject"}</button></>}</div></div>):<div className="sa-empty">{ar?"لا توجد دفعات.":"No payments found."}</div>}</div>}
function CompanyTable({rows,ar,full}:any){return <div className="sa-table co"><div className="sa-row head"><span>{ar?"الشركة":"Company"}</span><span>{ar?"الدولة":"Country"}</span><span>{ar?"الخطة":"Plan"}</span><span>{ar?"الحالة":"Status"}</span>{full&&<span>{ar?"انتهاء الاشتراك":"Subscription End"}</span>}</div>{rows.map((c:any)=><div className="sa-row" key={c.id}><div className="sa-company"><i>{(c.name||"N")[0].toUpperCase()}</i><b>{c.name}</b></div><span>{c.country||"—"}</span><b>{c.plan||"trial"}</b><Badge v={c.subscription_status} ar={ar}/>{full&&<small>{c.subscription_ends_at?new Date(c.subscription_ends_at).toLocaleDateString(ar?"ar-OM":"en-GB"):"—"}</small>}</div>)}</div>}