import{NextResponse}from"next/server";import{createClient}from"@supabase/supabase-js";export const runtime="nodejs";export async function GET(req:Request){const u=new URL(req.url);if(u.searchParams.get("hub.mode")==="subscribe"&&u.searchParams.get("hub.verify_token")===process.env.WHATSAPP_VERIFY_TOKEN)return new Response(u.searchParams.get("hub.challenge")||"",{status:200});return new Response("Forbidden",{status:403})}export async function POST(req:Request){const body=await req.json();try{const value=body?.entry?.[0]?.changes?.[0]?.value;const phoneId=value?.metadata?.phone_number_id;const incoming=value?.messages?.[0];if(!phoneId||!incoming?.text?.body)return NextResponse.json({ok:true});const admin=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!);const{data:conn}=await admin.from("channel_connections").select("*").eq("channel","whatsapp").eq("phone_number_id",phoneId).eq("status","connected").maybeSingle();if(!conn)return NextResponse.json({ok:true});let{data:contact}=await admin.from("contacts").select("*").eq("company_id",conn.company_id).eq("phone",incoming.from).maybeSingle();if(!contact){const r=await admin.from("contacts").insert({company_id:conn.company_id,phone:incoming.from,source:"whatsapp",name:value?.contacts?.[0]?.profile?.name||null}).select().single();contact=r.data}let{data:conv}=await admin.from("conversations").select("*").eq("company_id",conn.company_id).eq("contact_id",contact?.id).eq("channel","whatsapp").eq("status","open").maybeSingle();let emp:any=null;if(conv?.ai_employee_id){const r=await admin.from("ai_employees").select("*").eq("id",conv.ai_employee_id).maybeSingle();emp=r.data}else{const r=await admin.from("ai_employees").select("*").eq("company_id",conn.company_id).eq("status","active").order("created_at").limit(1).maybeSingle();emp=r.data}if(!conv){const r=await admin.from("conversations").insert({company_id:conn.company_id,contact_id:contact?.id,ai_employee_id:emp?.id||null,channel:"whatsapp",status:"open"}).select().single();conv=r.data}const text=incoming.text.body;await admin.from("messages").insert({conversation_id:conv.id,sender:"customer",content:text});
const lower=text.toLowerCase();
const handoffPatterns=["human","person","manager","agent","complaint","شكوى","موظف","شخص","مدير","مسؤول","احكي مع","أتحدث مع","اتحدث مع"];
const wantsHuman=handoffPatterns.some(x=>lower.includes(x));
if(wantsHuman){await admin.from("conversations").update({human_takeover:true}).eq("id",conv.id);await admin.from("messages").insert({conversation_id:conv.id,sender:"system",content:"Human takeover requested by customer."});return NextResponse.json({ok:true,handoff:true})}
if(conv.human_takeover||!emp)return NextResponse.json({ok:true});const[{data:knowledge},{data:history}]=await Promise.all([admin.from("knowledge_items").select("title,content").eq("company_id",conn.company_id),admin.from("messages").select("sender,content").eq("conversation_id",conv.id).order("created_at",{ascending:false}).limit(12)]);const knowledgeText=(knowledge||[]).map((k:any)=>"### "+k.title+"\n"+k.content).join("\n\n");const historyText=(history||[]).reverse().map((m:any)=>m.sender+": "+m.content).join("\n");const instructions=`You are ${emp.name}, an AI ${String(emp.role).replace("_"," ")} employee. Goal: ${emp.goal||"help the customer"}. Tone: ${emp.tone}. Language: ${emp.language}. Special instructions: ${emp.instructions||"None"}. Reply in the customer's language. Use only approved knowledge for business facts, prices, services and policies. If information is missing, say so and offer human help. Never invent facts. Keep WhatsApp replies concise and natural.\n\nAPPROVED KNOWLEDGE:\n${knowledgeText||"No approved knowledge."}`;const ai=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+process.env.OPENAI_API_KEY},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.6-luna",instructions,input:historyText,reasoning:{effort:"none"}})});const data=await ai.json();let answer=data.output_text;if(!answer&&Array.isArray(data.output))for(const item of data.output)if(Array.isArray(item.content))for(const part of item.content)if(part.type==="output_text"&&part.text)answer=(answer||"")+part.text;if(!answer)return NextResponse.json({ok:true,ai_error:data?.error?.message||"no answer"});
const salesSignals=["price","pricing","cost","quote","package","buy","book","interested","prices","how much","سعر","أسعار","اسعار","الأسعار","الاسعار","بكم","كم","تكلفة","عرض","باقة","باقات","اشتراك","مهتم","احجز","حجز"];
if(salesSignals.some(x=>lower.includes(x))){
 const{data:existingLead}=await admin.from("leads").select("id").eq("company_id",conn.company_id).eq("conversation_id",conv.id).maybeSingle();
 if(!existingLead){const{error:leadError}=await admin.from("leads").insert({company_id:conn.company_id,contact_id:contact?.id,ai_employee_id:emp.id,conversation_id:conv.id,stage:"new",notes:"Automatically qualified from WhatsApp conversation.",qualification:{source:"whatsapp",trigger_message:text}});if(leadError){console.error("Auto lead insert failed",leadError);await admin.from("messages").insert({conversation_id:conv.id,sender:"system",content:"Auto lead creation failed: "+leadError.message})}else{await admin.from("messages").insert({conversation_id:conv.id,sender:"system",content:"Lead created automatically from purchase intent."})}}
}
await admin.from("messages").insert({conversation_id:conv.id,sender:"ai",content:answer});const token=process.env.WHATSAPP_ACCESS_TOKEN;if(token)await fetch(`https://graph.facebook.com/v26.0/${phoneId}/messages`,{method:"POST",headers:{"Authorization":"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:incoming.from,type:"text",text:{body:answer}})});return NextResponse.json({ok:true})}catch(e){console.error("WhatsApp webhook",e);return NextResponse.json({ok:true})}}