import Link from"next/link";
const roles=[["Sales","Qualify inquiries, capture buying intent and move opportunities through your pipeline."],["Support","Answer customer questions instantly using your approved company knowledge."],["Bookings","Handle appointment and booking conversations around the clock."],["Follow-ups","Keep qualified opportunities moving without relying on manual reminders."],["Collections","Follow payment commitments and keep conversations organized."]];
export default function Home(){return <main className="landing">
<nav><Logo/><div className="navlinks"><a href="#product">Product</a><a href="#how">How it works</a><a href="#roles">AI Employees</a><a href="#pricing">Pricing</a><Link className="ghost" href="/login">Sign in</Link><Link className="button" href="/signup">Start Free</Link></div></nav>
<section className="hero"><div className="eyebrow">YOUR AI WORKFORCE</div><h1>Hire AI employees<br/>that actually get <span>work done.</span></h1><p>NAYROQ gives your business AI employees for sales, support, bookings and follow-ups — connected to the channels your customers already use.</p><div className="actions"><Link className="button large" href="/signup">Start 3-Day Free Trial →</Link><a className="ghost large" href="#how">See how NAYROQ works</a></div><div className="trust">Arabic + English · WhatsApp · Instagram · Facebook · Website</div></section>
<section className="proofstrip"><span><b>24/7</b> customer coverage</span><span><b>1 Inbox</b> across channels</span><span><b>AI + Human</b> takeover</span><span><b>CRM</b> built in</span><span><b>Revenue</b> attribution</span></section>
<section id="how" className="homeblock"><div className="sectionintro"><div className="eyebrow">HOW IT WORKS</div><h2>From customer message to business result.</h2><p>NAYROQ is more than a chatbot. It combines AI conversations, business knowledge, CRM and sales automation in one workspace.</p></div><div className="stepshome">{[["01","Teach it your business","Add services, prices, FAQs, policies and instructions to your Knowledge Base."],["02","Hire your AI employees","Choose the role, language, tone and goal for each AI employee."],["03","Connect your channels","Bring WhatsApp, website chat and supported social channels into one inbox."],["04","Track real outcomes","Follow leads, quotations, follow-ups, bookings, sales and revenue from one dashboard."]].map(x=><article key={x[0]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section id="roles" className="homeblock alt"><div className="sectionintro"><div className="eyebrow">BUILD YOUR TEAM</div><h2>Different jobs. One AI workforce.</h2><p>Each employee has a defined role and works from the same approved company knowledge.</p></div><div className="rolegrid">{roles.map((r,i)=><div className="role" key={r[0]}><div className="roleicon">{["↗","◉","▣","↻","◇"][i]}</div><h3>{r[0]}</h3><p>{r[1]}</p></div>)}</div></section>
<section className="homeblock"><div className="splitfeature"><div><div className="eyebrow">ONE UNIFIED INBOX</div><h2>Your customers can message anywhere.</h2><p>NAYROQ keeps conversations together so your team can see what the AI said, take over when needed and continue without losing context.</p><div className="checklist"><span>✓ WhatsApp Business</span><span>✓ Website Chat Widget</span><span>✓ Instagram messaging integration</span><span>✓ Facebook Messenger integration</span><span>✓ Human takeover</span></div></div><div className="mockpanel"><small>UNIFIED INBOX</small><div className="mockrow"><i>W</i><div><b>New pricing inquiry</b><span>WhatsApp · AI Sales Agent</span></div><em>Now</em></div><div className="mockrow"><i>⌁</i><div><b>Website visitor</b><span>Website · Human takeover</span></div><em>2m</em></div><div className="mockrow"><i>I</i><div><b>Product question</b><span>Instagram · AI Support</span></div><em>8m</em></div></div></div></section>
<section id="product" className="homeblock alt"><div className="splitfeature reverse"><div className="metriccard"><b>Today’s AI team</b><div className="metrics"><span><strong>186</strong>Conversations</span><span><strong>41</strong>Qualified leads</span><span><strong>9</strong>Sales</span><span><strong>3,420</strong>Revenue</span></div></div><div><div className="eyebrow">NOT A CHATBOT</div><h2>An AI team measured by results.</h2><p>Automatically identify buying intent, create leads, qualify opportunities and track the path from first conversation to closed sale.</p><div className="checklist"><span>✓ Automatic lead creation</span><span>✓ Smart qualification</span><span>✓ Quotations & follow-ups</span><span>✓ Won / Lost pipeline</span><span>✓ Revenue attribution</span></div></div></div></section>
<section className="homeblock"><div className="sectionintro"><div className="eyebrow">CONTROL THE AI</div><h2>Your knowledge. Your rules. Your brand.</h2><p>AI employees answer from the information you approve. Define their goals, tone, language and escalation rules. When a customer asks for a person, NAYROQ can pause the AI and surface the conversation for human attention.</p></div><div className="featurecards"><article><b>Knowledge Base</b><p>Services, pricing, FAQs, policies and business information in one source of truth.</p></article><article><b>Arabic + English</b><p>Operate across Gulf markets with bilingual AI employees and a bilingual platform.</p></article><article><b>Human Handoff</b><p>Take over sensitive or high-value conversations from the Unified Inbox.</p></article><article><b>Notifications</b><p>See conversations and situations that require your team’s attention.</p></article></div></section>
<section className="homeblock alt"><div className="splitfeature"><div><div className="eyebrow">AI MANAGER + ANALYTICS</div><h2>Know what your AI workforce is producing.</h2><p>See conversations, leads, qualified opportunities, quotations, sales and revenue — plus performance by channel and AI employee.</p></div><div className="funnelmock">{[["Conversations","1,284"],["Leads","214"],["Qualified","96"],["Quotations","38"],["Won","17"]].map((x,i)=><div key={x[0]}><span>{x[0]}</span><i style={{width:(100-i*16)+"%"}}/><b>{x[1]}</b></div>)}</div></div></section>
<section className="homeblock"><div className="sectionintro"><div className="eyebrow">BUILT FOR GULF BUSINESSES</div><h2>One platform. Many industries.</h2></div><div className="industries">{["Real Estate","Clinics & Healthcare","Salons & Beauty","Hotels & Hospitality","Restaurants","E-commerce","Professional Services","Automotive"].map(x=><span key={x}>{x}</span>)}</div></section>
<section id="pricing" className="homepricing"><div className="eyebrow">SIMPLE PRICING</div><h2>Start with 3 days free.</h2><p>Choose the AI workforce that fits your business. Upgrade as you grow.</p><div className="homeplans"><Plan name="STARTER" price="19" employees="1 AI Employee" conversations="1,500 conversations / month" extras={["WhatsApp + Website Chat","Leads & CRM"]}/><Plan featured name="BUSINESS · MOST POPULAR" price="39" employees="3 AI Employees" conversations="5,000 conversations / month" extras={["All customer channels","CRM, quotations & follow-ups","Analytics & AI Manager"]}/><Plan name="GROWTH" price="79" employees="Unlimited AI Employees" conversations="15,000 conversations / month" extras={["Full AI workforce platform","Advanced sales automation","Priority growth capacity"]}/></div><small className="trialnote">3-day free trial · Start without activating a paid subscription.</small></section>
<section className="finalcta"><div className="eyebrow">YOUR NEXT EMPLOYEE DOESN’T NEED A DESK.</div><h2>Build your AI workforce today.</h2><p>Start with one AI employee. Add more as your business grows.</p><Link className="button large" href="/signup">Start Your 3-Day Free Trial →</Link></section>
<footer><Logo/><span>A Final Arrow Company</span><div><Link href="/privacy">Privacy</Link><Link href="/data-deletion">Data Deletion</Link></div></footer>
</main>}
function Plan({name,price,employees,conversations,extras,featured=false}:any){return <article className={featured?"featured":""}><small>{name}</small><h3>{price} <em>OMR / month</em></h3><b>{employees}</b><span>{conversations}</span>{extras.map((x:string)=><span key={x}>{x}</span>)}<Link className="button" href="/signup">Start Free Trial →</Link></article>}
function Logo(){return <div className="logo"><i>N</i><b>NAYROQ</b></div>}